### GET ALL SPOTS ###
GET http://localhost:3000/spots

### CREATE A SPOT ###
POST http://localhost:3000/spots
Content-Type: application/json

{
  "name": "Spot"
}

### GET A SPOT ###
GET http://localhost:3000/spots/3

### UPDATE A SPOT ###
PATCH http://localhost:3000/spots/1
Content-Type: application/json

{
  "name": "Spot Changed"
}

### GET ALL USERS ###
GET http://localhost:3000/users

### CREATE A USER ###
POST http://localhost:3000/users
Content-Type: application/json

{
  "lastName": "Costa",
  "firstName": "Ricardo",
  "email": "rkosta@gmail.com",
  "token": "123456"
}

### GET A USER ###
GET http://localhost:3000/users/2

