### GET ALL BOOKINGS ###
GET http://localhost:3000/bookings
token: 222222

### GET A BOOKING ###
GET http://localhost:3000/bookings/1
token: 222222

### CREATE A BOOKING ###
POST http://localhost:3000/bookings/create?spot=1
token: 222222

### END A BOOKING ###
POST http://localhost:3000/bookings/15/end
token: 444444

