### GET ALL SPOTS ###
GET http://localhost:3000/spots
Authorization: 123456

### CREATE A SPOT ###
POST http://localhost:3000/spots
Content-Type: application/json
Authorization: 444444

{
  "name": "One more Spot"
}

### GET A SPOT ###
GET http://localhost:3000/spots/1
Authorization: 123456

### UPDATE A SPOT ###
PATCH http://localhost:3000/spots/1
Content-Type: application/json
Authorization: 444444

{
  "name": "Spot Changed"
}
