import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm';

@Entity()
/* The class `Spot` defines properties for an entity with an auto-generated `id` and a `name` field. */
export class Spot {
  @PrimaryGeneratedColumn()
  /* The line `id: number;` in the `Spot` class is defining a property named `id` with a type
  annotation of `number`. This property is used to store the unique identifier for each instance of
  the `Spot` entity. The `@PrimaryGeneratedColumn()` decorator above the `id` property indicates
  that this field will be auto-generated by the database system, typically as a primary key. */
  id: number;

  @Column({
    unique: true,
  })
  /* The line `name: string;` in the `Spot` class is defining a property named `name` with a type
  annotation of `string`. This property is used to store the name of each instance of the `Spot`
  entity. The `@Column()` decorator above the `name` property indicates that this field will be
  mapped to a column in the database table where the entity is stored. The `string` type annotation
  specifies that the `name` property can only hold string values. */
  name: string;
}
